/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.LU;

import Business.EcoSystem;
import Business.LU.LU_Company;
import Business.Role.LU_Employee;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sethu
 */
public class Lu_Drivers extends javax.swing.JPanel {

    /**
     * Creates new form Lu_Drivers
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    LU_Company company;
    public Lu_Drivers(JPanel userProcessContainer,EcoSystem ecosystem, LU_Company company) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.company = company;
        
        txtRole.setText("LU_Employee");
        txtRole.setEnabled(false);
        populateTable(ecosystem.getUserAccountDirectory(),company.getEmployeesList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRole = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtPassword = new javax.swing.JPasswordField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRole.setEditable(false);
        txtRole.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 163, 38));

        lblUsername.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("UserName : ");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 98, 22));

        title.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("LIST OF DRIVERS");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 420, 40));

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 163, 38));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 100, -1));

        lblPassword.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password : ");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 98, 22));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "UserName", "Role"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 540, 156));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 163, 38));

        btnEdit.setText("View");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 100, 100, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 230, 100, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 90, -1));

        lblRole.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Role : ");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 98, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/lu.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 810, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = table.getSelectedRow();
        if (selectedRowIndex >= 0){
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            UserAccount selectedRowData = (UserAccount) model.getValueAt(selectedRowIndex, 0);
            txtUsername.setText(selectedRowData.getUsername());
            txtPassword.setText(selectedRowData.getPassword());

            txtUsername.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Select a row to modify");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = table.getSelectedRow();
        if (selectedRowIndex >= 0){
            int input = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (input == 0) {
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                UserAccount selectedRowData = (UserAccount) model.getValueAt(selectedRowIndex, 0);
                String username = selectedRowData.getUsername();
                company.getEmployeesList().remove(username); // remove employee from the company
                ecosystem.getUserAccountDirectory().getUserAccountList().remove(selectedRowData); // remove userAccount from the userAccount directory
                clearInputs();
                refreshData();
                JOptionPane.showMessageDialog(this, "Delete Success");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a user to delete");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Boolean editFlag = !txtUsername.isEnabled();
        if(txtUsername.getText().length() <= 2) {
            JOptionPane.showMessageDialog(this, "Username should be atleast 2 characters!!", null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(txtPassword.getPassword().length <= 2) {
            JOptionPane.showMessageDialog(this, "Password should be atleast 2 characters!!", null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        String username = txtUsername.getText();
        char[] passwordArr = txtPassword.getPassword();
        String password = new String(passwordArr);
        Role role = new LU_Employee();
        if (editFlag) {
            UserAccount ua = ecosystem.getUserAccountDirectory().getUserAccountByUserName(username);
            if (ua != null) ua.setPassword(password);
            clearInputs();
            refreshData();
        } else {
            // check for unique userName and add user
            if (ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
                ecosystem.getUserAccountDirectory().createUserAccount(username, password, null, role); // useraccount created

                // add userName to employeeList in company
                ArrayList<String> newEmployeeList = company.getEmployeesList();
                newEmployeeList.add(username);
                company.setEmployeesList(newEmployeeList); // adding username to list
                refreshData();
                clearInputs();
            } else {
                JOptionPane.showMessageDialog(this, "Username already exists");
                return;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void goBack() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        
    }

    private void populateTable(UserAccountDirectory userAccountDirectory, ArrayList<String> employeesList) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)table.getModel();
        model.setRowCount(0);
        
        // loopthrough userName
        ArrayList<UserAccount> companyEmployeeList = new ArrayList<UserAccount>();
        for (String s: employeesList){
            UserAccount newUserAccount = userAccountDirectory.getUserAccountByUserName(s);
            if (newUserAccount != null) {
                companyEmployeeList.add(newUserAccount);
            }
        }
        
        for (UserAccount ua: companyEmployeeList){
            Object[] row = new Object[2];
           row[0] = ua;
           row[1] = ua.getRole();
           
           model.addRow(row);
        }
    }

    private void clearInputs() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtUsername.setEnabled(true);
    }

    private void refreshData() {
        populateTable(ecosystem.getUserAccountDirectory(),company.getEmployeesList());
    }
}
