/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.WSU;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WSU.WSU_Company;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sethu
 */
public class Wsu_AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form Wsu_AdminPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    WSU_Company company;
    public Wsu_AdminPanel(JPanel userProcessContainer,EcoSystem ecosystem, UserAccount account, WSU_Company company) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        this.company = company;
        
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManagers = new javax.swing.JButton();
        btnBids = new javax.swing.JButton();
        btnExpenditureAnalysis = new javax.swing.JButton();
        lblWSUOrg = new javax.swing.JLabel();
        lblWSUName = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManagers.setText("MANAGERS");
        btnManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagersActionPerformed(evt);
            }
        });
        add(btnManagers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 218, 35));

        btnBids.setText("BIDS");
        btnBids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBidsActionPerformed(evt);
            }
        });
        add(btnBids, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 218, 34));

        btnExpenditureAnalysis.setText("EXPENDITURE ANALYSIS");
        add(btnExpenditureAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 218, 35));

        lblWSUOrg.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        lblWSUOrg.setText("WSU Org:");
        add(lblWSUOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 39));

        lblWSUName.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        lblWSUName.setText("jLabel2");
        add(lblWSUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 221, 40));

        lblimg.setIcon(new javax.swing.ImageIcon("/Users/varunvuppala/Desktop/Manager_WSU.png")); // NOI18N
        add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagersActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myManagerList", new manageEmployeesJpanel(userProcessContainer,ecosystem,company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagersActionPerformed

    private void btnBidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidsActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myAuctionJPanel", new AuctionJpanel(userProcessContainer,ecosystem, account, company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBidsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBids;
    private javax.swing.JButton btnExpenditureAnalysis;
    private javax.swing.JButton btnManagers;
    private javax.swing.JLabel lblWSUName;
    private javax.swing.JLabel lblWSUOrg;
    private javax.swing.JLabel lblimg;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        lblWSUName.setText(company.getName());
    }
}
