/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.LU.LU_Company;

import Business.Organization;
import Business.VU.VU_Company;
import Business.WRU.WRU_Company;
import Business.WSU.WSU_Company;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        model.setRoot(new DefaultMutableTreeNode("Ecosystem"));
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren(); // remove existing children
        DefaultMutableTreeNode networkState = new DefaultMutableTreeNode("Massachusetts");
        root.add(networkState);
        DefaultMutableTreeNode wasteSortingUnit = new DefaultMutableTreeNode("Waste Sorting Unit");
        DefaultMutableTreeNode wasteRecyclingUnit = new DefaultMutableTreeNode("Waste Recycling Unit");
        DefaultMutableTreeNode logisticsUnit = new DefaultMutableTreeNode("Logistics Unit");
        DefaultMutableTreeNode volunteerUnit = new DefaultMutableTreeNode("Volunteer Unit");
        DefaultMutableTreeNode rewardsUnit = new DefaultMutableTreeNode("Rewards Unit");
        networkState.add(wasteSortingUnit);
        networkState.add(wasteRecyclingUnit);
        networkState.add(logisticsUnit);
        networkState.add(volunteerUnit);
        networkState.add(rewardsUnit);
        for (WSU_Company c: ecosystem.getWSUCompanyDirectory().getCompanies()){
            wasteSortingUnit.add(new DefaultMutableTreeNode(c.getName()));
        }
        for (WRU_Company c: ecosystem.getWRUCompanyDirectory().getCompanies()){
            wasteRecyclingUnit.add(new DefaultMutableTreeNode(c.getName()));
        }
        for (LU_Company c: ecosystem.getLUCompanyDirectory().getCompanies()){
            logisticsUnit.add(new DefaultMutableTreeNode(c.getName()));
        }
        for (VU_Company c: ecosystem.getVUCompanyDirectory().getCompanies()){
            volunteerUnit.add(new DefaultMutableTreeNode(c.getName()));
        }
//        for (RU_Company c: ecosystem.getRUCompanyDirectory().getCompanies()){
//            rewardsUnit.add(new DefaultMutableTreeNode(c.getName()));
//        }
       // Add the code for draw your system structure shown by JTree
       
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        btnWru = new javax.swing.JButton();
        btnLu = new javax.swing.JButton();
        btnVu = new javax.swing.JButton();
        btnWsu = new javax.swing.JButton();
        btnRu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTree.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTreeComponentShown(evt);
            }
        });
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 321, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWru.setText("Waste Recycle Units");
        btnWru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWruActionPerformed(evt);
            }
        });
        jPanel2.add(btnWru, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 212, 45));

        btnLu.setText("Logistics Unit");
        btnLu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuActionPerformed(evt);
            }
        });
        jPanel2.add(btnLu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 212, 45));

        btnVu.setText("Volunteer Unit");
        btnVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuActionPerformed(evt);
            }
        });
        jPanel2.add(btnVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 212, 45));

        btnWsu.setText("Waste Seggregating Units");
        btnWsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWsuActionPerformed(evt);
            }
        });
        jPanel2.add(btnWsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 212, 45));

        btnRu.setText("Rewards Unit");
        btnRu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuActionPerformed(evt);
            }
        });
        jPanel2.add(btnRu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 212, 45));

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel2.setText("REWARDS BASED WASTE MANAGEMENT SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 460, 39));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel1.setText("SYSTEM ADMIN PANEL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 23));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/mjipo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 590));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        
//        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
//        if(selectedNode!=null){
//            lblSelectedNode.setText(selectedNode.toString());
//        }
    }//GEN-LAST:event_jTreeValueChanged

    private void btnWsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWsuActionPerformed
        // TODO add your handling code here:
//        ManageCustomers myCustomerList = new ManageCustomers(userProcessContainer,ecosystem);
        userProcessContainer.add("myCustomerList", new SA_WsuPanel(userProcessContainer,ecosystem));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWsuActionPerformed

    private void btnWruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWruActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myCustomerList", new SA_WruPanel(userProcessContainer,ecosystem));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWruActionPerformed

    private void btnLuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myLogistics", new SA_LogisticsPanel(userProcessContainer,ecosystem));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLuActionPerformed

    private void btnVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myVolunteers", new SA_VolunteerPanel(userProcessContainer,ecosystem));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVuActionPerformed

    private void jTreeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTreeComponentShown
        // TODO add your handling code here:
        System.out.println("component is shown");
        populateTree();
    }//GEN-LAST:event_jTreeComponentShown

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        // TODO add your handling code here:
        System.out.println("focus is shown");
        populateTree();
    }//GEN-LAST:event_jPanel2FocusGained

    private void btnRuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        userProcessContainer.add("myRewardCompanies", new SA_RuPanel(userProcessContainer,ecosystem));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLu;
    private javax.swing.JButton btnRu;
    private javax.swing.JButton btnVu;
    private javax.swing.JButton btnWru;
    private javax.swing.JButton btnWsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
