/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.WRU;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WRU.WRU_Company;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sethu
 */
public class Wru_AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form Wru_AdminPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    WRU_Company company;
    public Wru_AdminPanel(JPanel userProcessContainer,EcoSystem ecosystem, UserAccount account, WRU_Company company) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        this.company = company;
        
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnManagers = new javax.swing.JButton();
        btnBids = new javax.swing.JButton();
        btnExpenditureAnalysis = new javax.swing.JButton();
        lblCompanyName = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Helvetica", 1, 22)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("ADMIN PANEL");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 40));

        btnManagers.setBackground(new java.awt.Color(255, 255, 255));
        btnManagers.setText("MANAGERS");
        btnManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagersActionPerformed(evt);
            }
        });
        add(btnManagers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 194, 35));

        btnBids.setBackground(new java.awt.Color(255, 255, 255));
        btnBids.setText("AUCTION WORK AREA");
        btnBids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBidsActionPerformed(evt);
            }
        });
        add(btnBids, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 194, 35));

        btnExpenditureAnalysis.setBackground(new java.awt.Color(255, 255, 255));
        btnExpenditureAnalysis.setText("EXPENDITURE ANALYSIS");
        btnExpenditureAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenditureAnalysisActionPerformed(evt);
            }
        });
        add(btnExpenditureAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 35));

        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCompanyName.setText("Company Name : ");
        add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, 22));

        txtCompanyName.setText("My CompanyName");
        add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 52, 142, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CREATE NEW BID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 194, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/WRU.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 790, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidsActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myBidList", new Wru_AdminBids(userProcessContainer,ecosystem,account,company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBidsActionPerformed

    private void btnManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagersActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("myManagerList", new Wru_Managers(userProcessContainer,ecosystem,company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagersActionPerformed

    private void btnExpenditureAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenditureAnalysisActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("mySuccessOrders", new Wru_SuccessfulOrders(userProcessContainer,ecosystem,account,company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnExpenditureAnalysisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("createNewBid", new Wru_CreateNewBid(userProcessContainer,ecosystem,account,company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBids;
    private javax.swing.JButton btnExpenditureAnalysis;
    private javax.swing.JButton btnManagers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtCompanyName;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        txtCompanyName.setText(company.getName());
    }
}
