/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.WRU;

import Business.Bid.Bid;
import Business.Bid.BidDirectory;
import Business.EcoSystem;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import Business.WRU.WRU_Company;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sethu
 */
public class Wru_AdminBids extends javax.swing.JPanel {

    /**
     * Creates new form Wru_AdminOnGoingBids
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    WRU_Company company;
    public Wru_AdminBids(JPanel userProcessContainer,EcoSystem ecosystem, UserAccount account, WRU_Company company) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        this.company = company;
        
        populateBids(ecosystem.getBidDirectory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOngoingBids = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompletedBids = new javax.swing.JTable();
        title1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("CURRENT BIDS");

        tblOngoingBids.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bid Id", "Order Id", "Waste Type", "Quantity (LBS)", "Cost ($)", "TimeStamp", "Reported By"
            }
        ));
        jScrollPane1.setViewportView(tblOngoingBids);

        btnCreate.setText("Create New Bid");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Order");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tblCompletedBids.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bid Id", "Order Id", "Waste Type", "Quanity (lbs)", "Cost ($)", "Decision TimeStamp", "Reported By", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblCompletedBids);

        title1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title1.setText("COMPLETED BIDS");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(31, 31, 31)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)))
                .addGap(84, 84, 84)
                .addComponent(title1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("createNewBid", new Wru_CreateNewBid(userProcessContainer,ecosystem,account,company));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblOngoingBids.getSelectedRow();
        if (selectedRowIndex >= 0) {
            DefaultTableModel model = (DefaultTableModel) tblOngoingBids.getModel();
            Bid selectedBid = (Bid) model.getValueAt(selectedRowIndex, 0);
            if (selectedBid.getBidStatus().equals("pending")) {
                int input = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (input == 0) {
                    ecosystem.getBidDirectory().removeBidById(selectedBid.getId()); // removes the bid from bid directory;
                    populateBids(ecosystem.getBidDirectory()); // refresh   
                }
            } else {
                JOptionPane.showMessageDialog(this, "Decision has already been made on this bid, cannot be deleted!!");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a bid to delete");
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCompletedBids.getSelectedRow();
        if (selectedRowIndex >= 0) {
            DefaultTableModel model = (DefaultTableModel) tblCompletedBids.getModel();
            Bid selectedBid = (Bid) model.getValueAt(selectedRowIndex, 0);
            if (selectedBid.getBidStatus().equals("success")) {
                Order o = ecosystem.getOrderDirectory().getOrderById(selectedBid.getOrderId());
                if (o != null) {
                    userProcessContainer.add("view order", new Wru_OrderDetails(userProcessContainer,ecosystem,account,company, o));
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Order details not present since the bid is failed");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a bid to view the order details");
            return;
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        populateBids(ecosystem.getBidDirectory());
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCompletedBids;
    private javax.swing.JTable tblOngoingBids;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables

    private void populateBids(BidDirectory bidDirectory) {
        DefaultTableModel model1 = (DefaultTableModel) tblOngoingBids.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblCompletedBids.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        
        for(Bid b: bidDirectory.getBidList()){
            if(b.getBidCompanyId() == company.getId()) {
                if (b.getBidStatus().equals("pending")) {
                    Object[] row1 = new Object[7];
                    row1[0] = b;
                    row1[1] = b.getOrderId();
                    row1[2] = "N/A";
                    row1[3] = "N/A";
                    Order o = ecosystem.getOrderDirectory().getOrderById(b.getOrderId());
                    if(o != null) {
                        row1[2] = o.getWasteType();
                        row1[3] = o.getQuantity();
                    }
                    row1[4] = b.getBidValue();
                    row1[5] = b.getBidTimeStamp();
                    row1[6] = b.getBidUserName();

                    model1.addRow(row1);    
                } else {
                    Object[] row1 = new Object[8];
                    row1[0] = b;
                    row1[1] = b.getOrderId();
                    row1[2] = "N/A";
                    row1[3] = "N/A";
                    Order o = ecosystem.getOrderDirectory().getOrderById(b.getOrderId());
                    if(o != null) {
                        row1[2] = o.getWasteType();
                        row1[3] = o.getQuantity();
                    }
                    row1[4] = b.getBidValue();
                    row1[5] = "N/A";
                    if (o != null) {
                        row1[5] = o.getBuyingTimeStamp();
                    }
                    row1[6] = b.getBidUserName();
                    row1[7] = b.getBidStatus();

                    model2.addRow(row1); 
                }
            }
        }

    }

    private void goBack() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);   
    }
}
